# Run complete R workflow after the shared raw CSV exists. Run from the repository root.
source("r/scripts/01_generate_synthetic_data.R")
source("r/scripts/02_clean_sort_define.R")
source("r/scripts/03_data_quality.R")
source("r/scripts/04_descriptive_epi.R")
source("r/scripts/05_comparative_measures.R")
source("r/scripts/06_correlation_analysis.R")
source("r/scripts/07_linear_regression.R")
source("r/scripts/08_logistic_regression.R")
source("r/scripts/09_time_series_analysis.R")
source("r/scripts/10_survival_analysis.R")
source("r/scripts/11_sensitivity_analysis.R")
source("r/scripts/12_generate_dashboard_exports.R")
source("r/scripts/13_monitoring_and_evaluation.R")
message("Complete R workflow completed.")
