library(dplyr); library(readr)
analysis <- read_csv("data/processed/r_analysis_ready.csv", show_col_types=FALSE)
dir.create("outputs/r/descriptive", recursive=TRUE, showWarnings=FALSE)
by_year <- analysis %>% group_by(visit_year) %>% summarise(visits=n(), providers=n_distinct(provider_id), noncompliance_rate_pct=round(mean(noncompliant)*100,1), mean_compliance_score=round(mean(compliance_score),2), .groups="drop")
write_csv(by_year, "outputs/r/descriptive/noncompliance_by_year.csv")
by_type <- analysis %>% group_by(provider_type) %>% summarise(visits=n(), providers=n_distinct(provider_id), noncompliance_rate_pct=round(mean(noncompliant)*100,1), mean_compliance_score=round(mean(compliance_score),2), .groups="drop")
write_csv(by_type, "outputs/r/descriptive/noncompliance_by_provider_type.csv")
domains <- tibble(domain=c("Training","Eligibility","Documentation","Inventory","Storage/Handling"), rate=c(mean(analysis$training_compliant_bin==0), mean(analysis$eligibility_compliant_bin==0), mean(analysis$documentation_compliant_bin==0), mean(analysis$inventory_compliant_bin==0), mean(analysis$storage_handling_compliant_bin==0))*100) %>% mutate(noncompliance_rate_pct=round(rate,1)) %>% select(domain, noncompliance_rate_pct) %>% arrange(desc(noncompliance_rate_pct))
write_csv(domains, "outputs/r/descriptive/domain_noncompliance_summary.csv")
metrics <- tibble(metric=c("analysis_ready_records","unique_providers","overall_noncompliance_pct","top_noncompliance_domain"), value=c(nrow(analysis), n_distinct(analysis$provider_id), round(mean(analysis$noncompliant)*100,1), domains$domain[1]))
write_csv(metrics, "outputs/r/descriptive/summary_metrics.csv")
