library(readr); library(broom); library(dplyr)
analysis <- read_csv("data/processed/r_analysis_ready.csv", show_col_types=FALSE)
dir.create("outputs/r/logistic_regression", recursive=TRUE, showWarnings=FALSE)
analysis$provider_type <- relevel(factor(analysis$provider_type), ref="Public Health Clinic")
analysis$rural_urban <- relevel(factor(analysis$rural_urban), ref="Urban")
analysis$time_in_program_cat <- relevel(factor(analysis$time_in_program_cat), ref="4-7 years")
model <- glm(noncompliant ~ provider_type + rural_urban + time_in_program_cat + log_doses_administered + site_visit_delay_days + staff_turnover + prior_technical_assistance + prior_noncompliance + factor(visit_year), data=analysis, family=binomial())
out <- tidy(model, conf.int=TRUE, exponentiate=TRUE) %>% filter(term != "(Intercept)")
write_csv(out, "outputs/r/logistic_regression/logistic_regression_adjusted_odds_ratios.csv")
writeLines(capture.output(summary(model)), "outputs/r/logistic_regression/logistic_regression_summary.txt")
