library(dplyr); library(readr); library(lubridate); library(zoo)
analysis <- read_csv("data/processed/r_analysis_ready.csv", show_col_types=FALSE) %>% mutate(visit_date=ymd(visit_date))
dir.create("outputs/r/time_series", recursive=TRUE, showWarnings=FALSE)
monthly <- analysis %>% mutate(visit_month=floor_date(visit_date,"month")) %>% group_by(visit_month) %>% summarise(visits=n(), noncompliance_rate_pct=round(mean(noncompliant)*100,1), .groups="drop") %>% mutate(rolling_3_month_rate_pct=round(zoo::rollmean(noncompliance_rate_pct,3,fill=NA,align="right"),1))
write_csv(monthly, "outputs/r/time_series/monthly_noncompliance_trends.csv")
quarterly <- analysis %>% group_by(visit_quarter) %>% summarise(visits=n(), noncompliance_rate=mean(noncompliant), .groups="drop") %>% arrange(visit_quarter) %>% mutate(quarter_index=row_number(), post_policy=ifelse(visit_quarter >= "2022Q3",1,0), quarters_after_policy=pmax(0, quarter_index - min(quarter_index[post_policy==1]) + 1))
write_csv(quarterly, "outputs/r/time_series/quarterly_noncompliance_trends.csv")
model <- lm(noncompliance_rate ~ quarter_index + post_policy + quarters_after_policy, data=quarterly)
write_csv(broom::tidy(model, conf.int=TRUE), "outputs/r/time_series/segmented_trend_model.csv")
