library(dplyr); library(readr)
clean <- read_csv("data/processed/r_cleaned_all_visits.csv", show_col_types=FALSE)
analysis <- read_csv("data/processed/r_analysis_ready.csv", show_col_types=FALSE)
dir.create("outputs/r/sensitivity", recursive=TRUE, showWarnings=FALSE)
valid_base <- clean %>% filter(invalid_visit_date==0, future_visit_date==0, visit_year >= 2019, visit_year <= 2025, provider_type != "Unknown", rural_urban != "Unknown", jurisdiction_valid==1)
valid_base <- valid_base %>% mutate(noncompliant_missing_as_noncomp=ifelse(missing_domain_count > 0 | ifelse(is.na(domain_noncompliance_count),0,domain_noncompliance_count) > 0,1,0))
alt <- valid_base %>% filter(complete_visit_excluding_training==1, !is.na(doses_administered_clean), !is.na(years_in_program))
out <- tibble(analysis=c("primary_complete_visit","missing_domains_as_noncompliant","outcome_excluding_training_domain"), records=c(nrow(analysis), nrow(valid_base), nrow(alt)), noncompliance_pct=c(round(mean(analysis$noncompliant)*100,1), round(mean(valid_base$noncompliant_missing_as_noncomp)*100,1), round(mean(alt$noncompliant_excluding_training)*100,1)))
write_csv(out, "outputs/r/sensitivity/sensitivity_summary.csv")
